import { Inter } from 'next/font/google';

import StyledComponentsRegistry from '@/lib/registry';
import type {} from 'styled-components/cssprop';

import { Modal } from '@hooks/use-modal';
import ModalProvider from '@hooks/use-modal/provider/ModalProvider';

import type { Metadata } from 'next';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <ModalProvider>
            {children}
            <div id='modal' />
            <Modal />
          </ModalProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
